### site metadata ###

site_name: Fahmi's Project Library
site_description : Project tech stacks and description detailed by fahmi wahyu wiradika 

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/fahmiwazu/docs-portfolio?tab=MIT-1-ov-file#" target="_blank" rel="noopener"> Fahmi Wahyu Wiradika</a>

### Site Settings ###
#theme : readthedocs --- Optional to use if we don't like to use material theme
theme: 
  name: material
  icon:
    annotation: material/arrow-right-circle-outline
    logo: material/bullseye-arrow
    menu: material/bullseye-arrow
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - navigation.tracking
    - navigation.path
    - navigation.tabs.sticky
    - navigation.footer
    - tabs: true
    ### If page want to be divided to 3 parts then uncomment toc.follow, either using toc.integrate
    # - toc.integrate 
    - toc.follow 
  language: en
  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: indigo
  # Palette toggle for dark mode    
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: deep orange
  font: 
    text: Roboto
    code: Roboto Mono

#extra_css:
#  - stylesheets/extra.css

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/fahmiwazu
  - icon: simple/postman
    link: https://www.postman.com/fahmi-wiradika
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/fahmiwiradika96/
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/fahmiwazu
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Indonesia
  #     link: /id/
  #     lang: id

### Navigation Settings ###
### Please to uncomment the document that ready only !!!! ###
nav:
  - Home : index.md
  - Introduction : 
    - About Fahmi: introduction/About-fahmi.md
    - Experience : introduction/Experience-fahmi.md
    - Certification: introduction/Certification-fahmi.md
  - Assignment Project :
    - freeCodeCamp:
      - Relational Database : 
        - Celestial Bodies Database: projects/assignment/relationalDatabase/celestialDB.md
        - World Cup Database: projects/assignment/relationalDatabase/worldCupDB.md
        - Salon Appointment Scheduler: projects/assignment/relationalDatabase/salonDB.md
        - Periodic Table Database: projects/assignment/relationalDatabase/periodicTable.md
        - Number Guessing Game: projects/assignment/relationalDatabase/numberGuessing.md
#      - Back End Development and APIs:
#        - Timestamp Microservice: projects/assignment/backendAPI/timeStamp.md
#        - Request Header Parser Microservice: projects/assignment/backendAPI/reqHeaderParser.md
#        - URL Shortener Microservice: projects/assignment/backendAPI/urlShortener.md
#        - Exercise Tracer: projects/assignment/backendAPI/exerciseTable.md
#        - File Metadata Microservice: projects/assignment/backendAPI/fileMetadata.md
      - Quality Assurance: 
#        - Metric-Imperial Converter: projects/assignment/qualityAssurance/metricImperialConverter.md
#        - Issue Tracker: projects/assignment/qualityAssurance/issueTracker.md
#        - Personal Library: projects/assignment/qualityAssurance/personalLibrary.md
#        - Sudoku Solver: projects/assignment/qualityAssurance/sudokuSolver.md
        - American-British Translator: projects/assignment/qualityAssurance/american-britishTranslator.md
    - Postman :  
      - API Test Automation: projects/assignment/postman/postmanAutomation.md
  - Data Structure & Algorithm :
    - Web Quiz Automation: projects/dataStructureAlgorithm/webQuiz.md
#    - Flexible FizzBuzz Concat: projects/dataStructureAlgorithm/flexibleFizzBuzz.md
#    - Fibonacci Indexes Finder: projects/dataStructureAlgorithm/fibonacciIndex.md
#    - Longest Palindrome : projects/dataStructureAlgorithm/longestPalindrome.md
#  - Sample of Work:
#    - Java Automation Test: projects/workSample/javaAutomation.md
#    - Python Automation Test: projects/workSample/pythonAutomation.md
#  - Academic Research:
#    - Bachelor Research:
#      - Smart Metering Systems:
#        - Overview: projects/academic/overview.md
#        - Chapter 1: projects/academic/chapterOne.md
#        - Chapter 2: projects/academic/chapterTwo.md
#        - Chapter 3: projects/academic/chapterThree.md
#        - Chapter 4: projects/academic/chapterFour.md

# Extensions  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  - git-revision-date-localized
  - glightbox