### site metadata ###

site_name: Fahmi's Project Library
site_description : Project tech stacks and description detailed by fahmi wahyu wiradika 

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/fahmiwazu/docs-portfolio?tab=MIT-1-ov-file#" target="_blank" rel="noopener"> Fahmi Wahyu Wiradika</a>

### Site Settings ###
#theme : readthedocs --- Optional to use if we don't like to use material theme
theme: 
  name: material
  icon:
    annotation: material/arrow-right-circle-outline
    logo: material/bullseye-arrow
    menu: material/bullseye-arrow
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - navigation.tracking
    - navigation.path
    - navigation.tabs.sticky
    - navigation.footer
    - tabs: true
    ### If page want to be divided to 3 parts then uncomment toc.follow, either using toc.integrate
    # - toc.integrate 
    - toc.follow 
  language: en
  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: indigo
  # Palette toggle for dark mode    
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: deep orange
  font: 
    text: Roboto
    code: Roboto Mono

#extra_css:
#  - stylesheets/extra.css

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/fahmiwazu
  - icon: simple/postman
    link: https://www.postman.com/fahmi-wiradika
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/fahmiwiradika96/
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/fahmiwazu
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Indonesia
  #     link: /id/
  #     lang: id

### Navigation Settings ###
### Please to uncomment the document that ready only !!!! ###
nav:
  - Home : index.md
  - Introduction : 
    - About Fahmi: Introduction/About-fahmi.md
    - Experience : Introduction/Experience-fahmi.md
    - Certification: Introduction/Certification-fahmi.md
  - Open Source Project :
    - freeCodeCamp:
      - Relational Database : 
        - Celestial Bodies Database: Projects/Open-Source/rdb/project1.md
        - World Cup Database: Projects/Open-Source/rdb/project2.md
        - Salon Appointment Scheduler: Projects/Open-Source/rdb/project3.md
        - Periodic Table Database: Projects/Open-Source/rdb/project4.md
        - Number Guessing Game: Projects/Open-Source/rdb/project5.md
      - Back End Development and APIs: 
        - Timestamp Microservice: Projects/Open-Source/bedaa/project1.md
        - Request Header Parser Microservice: Projects/Open-Source/bedaa/project2.md
        - URL Shortener Microservice: Projects/Open-Source/bedaa/project3.md
        - Exercise Tracer: Projects/Open-Source/bedaa/project4.md
        - File Metadata Microservice: Projects/Open-Source/bedaa/project5.md
      - Quality Assurance: 
        - Metric-Imperial Converter: Projects/Open-Source/qa/project1.md
        - Issue Tracker: Projects/Open-Source/qa/project2.md
        - Personal Library: Projects/Open-Source/qa/project3.md
        - Sudoku Solver: Projects/Open-Source/qa/project4.md
        - American-British Translator: Projects/Open-Source/qa/project5.md
    # - Katalon : 
    #   - API Automation: Projects/Open-Source/katalon-api.md
    #   - Web UI Automation: Projects/Open-Source/katalon-web-ui.md
    - Postman :  
      - API Test Automation: Projects/Open-Source/postman-api-auto.md
  - Personal Project : 
    - 1to50 Puzzle: Projects/Personal/1to50.md
    # - Car Rental: Projects/Personal/car-rental.md
    # - CRUD App: Projects/Personal/simple-be-app.md
    # - Melaka : Projects/Personal/melaka.md
  # - Professional Project: 
  #     - Desktop Automation Tools: Projects/Professional/desktop-app.md
  #     - .NET Automation Script: Projects/Professional/dotnet-app.md
  # - Academic Project:
  #   - Smart Metering Systems: Projects/Academic/final-prj.md

# Extensions  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  - git-revision-date-localized
  - glightbox